### ISSUE TITLE
Warning after installation

### ISSUE THREAD

**Issue by chefranci** [RIPE-NCC/wordpress-meeting-support-plugin#1]
any suggestion? 

Warning: include_once(/var/www/html/wp-content/plugins/wordpress-meeting-support-plugin/includes/crowd.inc.php): failed to open stream: No such file or directory in /var/www/html/wp-content/plugins/wordpress-meeting-support-plugin/includes/class-meeting-support-authentication.php on line 40

Warning: include_once(): Failed opening '/var/www/html/wp-content/plugins/wordpress-meeting-support-plugin/includes/crowd.inc.php' for inclusion (include_path='.:/usr/local/lib/php') in /var/www/html/wp-content/plugins/wordpress-meeting-support-plugin/includes/class-meeting-support-authentication.php on line 40

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/plugins/wordpress-meeting-support-plugin/includes/class-meeting-support-authentication.php:40) in /var/www/html/wp-admin/includes/misc.php on line 1126

**Comment by olipayne** [comment]
These are just warnings. Has the plugin failed to activate?

**Comment by chefranci** [comment]
It did activate but couldn’t go any further on setting the options because of the persistence of the warnings.
What is the crowd file?

**Comment by joshuajosh59** [comment]
The same thing happened to me, whats the solution!
```
Warning: require_once(/home/ngnog/web/www/public_html/wp-content/plugins/wordpress-meeting-support-plugin-master/vendor/autoload.php): failed to open stream: No such file or directory in /home/ngnog/web/www/public_html/wp-content/plugins/wordpress-meeting-support-plugin-master/includes/class-meeting-support.php on line 122

Fatal error: require_once(): Failed opening required '/home/ngnog/web/wwwpublic_html/wp-content/plugins/wordpress-meeting-support-plugin-master/vendor/autoload.php' (include_path='.:/usr/share/php') in /home/ngnog/web/www/public_html/wp-content/plugins/wordpress-meeting-support-plugin-master/includes/class-meeting-support.php on line 122
```

**Comment by momorientes** [comment]
stuck on the same issue with a fresh installation of wordpress 4.9.8.

```
Warning: require_once(/var/www/vote/wp-content/plugins/wordpress-meeting-support-plugin/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/vote/wp-content/plugins/wordpress-meeting-support-plugin/includes/class-meeting-support.php on line 122

Fatal error: require_once(): Failed opening required '/var/www/vote/wp-content/plugins/wordpress-meeting-support-plugin/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/vote/wp-content/plugins/wordpress-meeting-support-plugin/includes/class-meeting-support.php on line 122
```

**Comment by olipayne** [comment]
@joshuajosh59 and @momorientes - autoload.php is auto-generated once the plugin install has completed, this can take up to 30 seconds while it fetches vendor libraries. If it doesn't happen then please paste the debug.log contents as another issue
